stages:
     - deploy   
rules-job:
     stage: deploy
     tags: ["sync"]
     rules:
      - changes:
        - ".gitlab-ci.yml"
        when: never
      - when: always
      - changes:
        - result/*
      #   - if  ! grep "\.ndjson$" <(git diff --name-only HEAD~1); then exit; fi; 
     script:
         - cat $input
         - echo "${CI_COMMIT_SHA}"
         - pwd 
         - echo "${CI_PROJECT_DIR}"
         - ls -l ${CI_PROJECT_DIR}/rules/_deprecated/
         - cd ${CI_PROJECT_DIR}/rules/_deprecated/
         - for rule in *.toml;do ls $rule >> deprecatedrules;done
         - cp -p deprecatedrules /home/gitlab-runner/sync-rules/
         - cp /home/gitlab-runner/sync-rules/script.sh cd ${CI_PROJECT_DIR}/rules/_deprecated/
         - bash ${CI_PROJECT_DIR}/rules/_deprecated/script.sh