stages:
     - deploy   
rules-job:
     stage: deploy
     tags: ["sync"]
     rules:
      - changes:
        - ".gitlab-ci.yml"
        when: never
      - when: always
      - changes:
        - result/*
      #   - if  ! grep "\.ndjson$" <(git diff --name-only HEAD~1); then exit; fi; 
     script:
         - cat $input
         - echo "${CI_COMMIT_SHA}"
         - loc=$(pwd)
         - rule=`git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA`
         - echo $rule | tr " " "\n" | grep result > resultrules
         - cp -r ${CI_PROJECT_DIR} /home/gitlab-runner/
         - cd /home/gitlab-runner/octorules
         - cp ../sync-rules/handler.sh .
         - bash handler.sh $input


         - cd ${CI_PROJECT_DIR}/rules/_deprecated/
         - for rule in *.toml;do ls $rule >> deprecatedrules;done
         - if cmp --silent -- deprecatedrules /home/gitlab-runner/sync-rules/deprecatedrules; then ans=1 ;else ans=2 && grep -F -x -v -f /home/gitlab-runner/sync-rules/deprecatedrules deprecatedrules >> /home/gitlab-runner/sync-rules/newdeprecatedrules && cp -p deprecatedrules /home/gitlab-runner/sync-rules/ ; fi
         - bash /home/gitlab-runner/sync-rules/depsync.sh $ans