stages:
     - deploy   
rules-job:
     stage: deploy
     tags: ["sync"]
     rules:
      - changes:
        - ".gitlab-ci.yml"
        when: never
      - when: always
      - changes:
        - result/*
      #   - if  ! grep "\.ndjson$" <(git diff --name-only HEAD~1); then exit; fi; 
     script:
         - cat $input
         - echo "${CI_COMMIT_SHA}"
         - loc=$(pwd)
         - rule=`git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA`
         - echo $rule
         #- echo $rule | tr " " "\n" | grep result > resultrules
         #- cat resultrules
         - if [ ! -d /home/ubuntu/fromsync/"$(date +"%d-%m-%Y")" ]; then mkdir /home/ubuntu/fromsync/"$(date +"%d-%m-%Y")";fi
         - cp -r ${CI_PROJECT_DIR} /home/ubuntu/fromsync/"$(date +"%d-%m-%Y")"
         - cd /home/ubuntu/fromsync/"$(date +"%d-%m-%Y")"/octorules
         - cp ../../deprecated.sh .
         - for rule in ./rules/_deprecated/*toml; do grep -m 1 "^name =" $rule | awk -F\" '{print $2}'>> deprecated;done
         - bash deprecated.sh deprecated
         - cp ../../handler.sh .
         - bash handler.sh $input