name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Print input
        run: cat ${{ github.event.inputs.input }}
      - name: Print commit SHA
        run: echo "${{ github.sha }}"
      - name: echo pwd & init
        run: pwd && git init
      - name: Get changed files
        run: git diff-tree --no-commit-id --name-only -r $GITHUB_SHA
      - name: Filter result files
        run: |
          changed_files=$(git diff-tree --no-commit-id --name-only -r $GITHUB_SHA)
          echo $changed_files
          if echo "$changed_files" | grep -q result; then
            echo "$changed_files" | tr " " "\n" | grep result > resultrules
          fi
          if [ -e resultrules ]; then cat resultrules; fi
      - name: Sync code
        run: |
          if [ ! -d /home/ubuntu/fromsync/"$(date +"%d-%m-%Y")" ]; then
            mkdir /home/ubuntu/fromsync/"$(date +"%d-%m-%Y")"
          fi
          cp -r ${{ github.workspace }} /home/ubuntu/fromsync/"$(date +"%d-%m-%Y")"
          cd /home/ubuntu/fromsync/"$(date +"%d-%m-%Y")"/octorules
          cp ../../deprecated.sh .
          if [ -e deprecated ]; then
            rm deprecated
          fi
          for rule in ./rules/_deprecated/*toml; do
            grep -m 1 "^name =" $rule | awk -F\" '{print $2}' >> deprecated
          done
          bash deprecated.sh deprecated
          cp ../../handler.sh .
          bash handler.sh ${{ github.event.inputs.input }}
