name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
           fetch-depth: 0
      - name: Get changes
        run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
      - name: Filter result files
        run: |
          changed_files=$(git diff-tree --no-commit-id --name-only -r ${{github.sha}})
          echo $changed_files
          if echo "$changed_files" | grep -q result; then
            echo "$changed_files" | tr " " "\n" | grep result > resultrules
          fi
          if [ -e resultrules ]; then cat resultrules; fi
      - name: Sync code
        run: |
          if [ ! -d /home/ubuntu/fromsync/"$(date +"%d-%m-%Y")" ]; then
             mkdir /home/ubuntu/fromsync/"$(date +"%d-%m-%Y")"
          fi
          sudo cp -r ${{ github.workspace }} /home/ubuntu/fromsync/"$(date +"%d-%m-%Y")"
          cd /home/ubuntu/fromsync/"$(date +"%d-%m-%Y")"/octorules
          sudo cp ../../deprecated.sh .
          if [ -e deprecated ]; then
            rm deprecated
          fi
          for rule in ./rules/_deprecated/*toml; do
            sudo grep -m 1 "^name =" $rule | awk -F\" '{print $2}' >> deprecated
          done
          sudo bash deprecated.sh deprecated
          sudo cp ../../handler.sh .
          sudo bash handler.sh 
      
