name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Get modified files
        id: get-modified-files
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
      - name: Print input
        run: cat ${{ github.event.inputs.input }}
      - name: Print commit SHA
        run: echo "${{github.sha}}"
      - name: echo pwd & init
        run: pwd && git init
      - name: Get committed files
        id: get-committed-files
        run: |
          git fetch --unshallow || true
          files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
          echo "::set-output name=files::$files"  
      - name: cat 
        run:  echo ${{ steps.get-committed-files.outputs.files }}
      - name: Filter result files
        run: |
          get-modified-files=$(git diff-tree --no-commit-id --name-only -r ${{github.sha}})
          echo $changed_files
          echo "::set-output name=modified_files::$modified_files"
          if echo "$get-modified-files" | grep -q result; then
            echo "$get-modified-files" | tr " " "\n" | grep result > resultrules
          fi
          if [ -e resultrules ]; then cat resultrules; fi
      - name: Sync code
        run: |
          if [ ! -d /home/ubuntu/fromsync/"$(date +"%d-%m-%Y")" ]; then
            mkdir /home/ubuntu/fromsync/"$(date +"%d-%m-%Y")"
          fi
          cp -r ${{ github.workspace }} /home/ubuntu/fromsync/"$(date +"%d-%m-%Y")"
          cd /home/ubuntu/fromsync/"$(date +"%d-%m-%Y")"/octorules
          cp ../../deprecated.sh .
          if [ -e deprecated ]; then
            rm deprecated
          fi
          for rule in ./rules/_deprecated/*toml; do
            grep -m 1 "^name =" $rule | awk -F\" '{print $2}' >> deprecated
          done
          bash deprecated.sh deprecated
          cp ../../handler.sh .
          bash handler.sh ${{ github.event.inputs.input }}
